Implement query throttling
akkadotnet/Akka.Persistence.Linq2Db pull request #485
Opened 2024-10-08 07:00 UTC by Arkatufus

Implement query throttling scheme, similar to https://github.com/akkadotnet/akka.net/pull/6436

## Changes

* Add new `akka.persistence.query.journal.sql.max-concurrent-queries` HOCON setting
* Port `QueryThrottler` class
* Make sure that all query DB operations are guarded by throttle permit

2024-10-08 07:12 UTC, Arkatufus reviewed
Design self-review

2024-10-08 07:12 UTC, Arkatufus commented on src/Akka.Persistence.Sql/Extensions/ConnectionFactoryExtensions.cs
> +            }
This is the query throttling mechanism, we always ask for a permission before we execute any DB operations

2024-10-08 07:12 UTC, Arkatufus commented on src/Akka.Persistence.Sql/Extensions/ConnectionFactoryExtensions.cs
> +            }
This is the query throttling mechanism, we always ask for a permission before we execute any DB operations

2024-10-08 07:12 UTC, Arkatufus commented on src/Akka.Persistence.Sql/Query/Dao/BaseByteReadArrayJournalDao.cs
> +                    return await input._dbStateHolder.ExecuteQueryWithTransactionAsync(
Replace all `ExecuteWithTransactionAsync()` method call inside the read journal with `ExecuteQueryWithTransactionAsync()` to make sure that all DB queries are throttled

2024-10-10 14:18 UTC, Aaronontheweb requested changes
Need to add query timeouts

2024-10-10 14:18 UTC, Aaronontheweb commented on src/Akka.Persistence.Sql.Hosting/HostingExtensions.cs
> +            int? maxConcurrentQueries = null)
Technically a breaking change without a method overload, but I don't think there's any other meta-packages built on top of Akka.Persistence.Sql.Hosting so it's probably fine as it's source-compatible

2024-10-10 14:18 UTC, Aaronontheweb commented on src/Akka.Persistence.Sql/Extensions/ConnectionFactoryExtensions.cs
> +            await queryPermitter.Ask<QueryStartGranted>(RequestQueryStart.Instance);
This should use a timeout or a CTS

2024-10-10 14:18 UTC, Aaronontheweb commented on src/Akka.Persistence.Sql/Extensions/ConnectionFactoryExtensions.cs
> +            await queryPermitter.Ask<QueryStartGranted>(RequestQueryStart.Instance);
Should use a timeout or a CTS

2024-10-11 14:33 UTC, Arkatufus commented on src/Akka.Persistence.Sql/Extensions/ConnectionFactoryExtensions.cs
> +            await queryPermitter.Ask<QueryStartGranted>(RequestQueryStart.Instance);
done

2024-10-11 14:33 UTC, Arkatufus commented on src/Akka.Persistence.Sql/Extensions/ConnectionFactoryExtensions.cs
> +            await queryPermitter.Ask<QueryStartGranted>(RequestQueryStart.Instance);
done

2024-10-23 16:24 UTC, Aaronontheweb approved these changes

2024-10-23 16:24 UTC, merged